#!/usr/bin/env node
/**
 * Align sdkwork-llm domain naming with intelligence/llm capability.
 * Removes memory-template path/type/table debt while preserving behavior.
 */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const skipDirs = new Set(["target", "node_modules", ".git", ".pnpm"]);
const textExtensions = new Set([
  ".rs", ".toml", ".json", ".md", ".mjs", ".js", ".ts", ".yaml", ".yml", ".ps1", ".sql", ".txt",
]);

/** Longest-first replacement pairs for authored sources. */
const replacements = [
  ["/llm/v3/api/memory", "/llm/v3/api/llm"],
  ["/app/v3/api/memory", "/app/v3/api/llm"],
  ["/backend/v3/api/memory", "/backend/v3/api/llm"],
  ["${llmOpenApiPrefix}/memory", "${llmOpenApiPrefix}/llm"],
  ["sdkwork.memory.plugin", "sdkwork.llm.plugin"],
  ["runtime Memory plugin", "runtime LLM plugin"],
  ["OpenMemoryService", "OpenLlmService"],
  ["MemoryProductService", "LlmProductService"],
  ["NativeSqlMemoryStore", "NativeSqlLlmStore"],
  ["NativeSqlMemoryRecordDetail", "NativeSqlLlmRecordDetail"],
  ["NativeSqlOpenApiEventRow", "NativeSqlOpenApiEventRow"],
  ["MemoryDatabaseHost", "LlmDatabaseHost"],
  ["MemoryDatabasePool", "LlmDatabasePool"],
  ["MemoryDataPlane", "LlmDataPlane"],
  ["MemoryBackendRequestContext", "LlmBackendRequestContext"],
  ["MemoryOpenApiRequestContext", "LlmOpenApiRequestContext"],
  ["MemoryImplementationKind", "LlmImplementationKind"],
  ["MemoryPluginManifest", "LlmPluginManifest"],
  ["MemorySpiError", "LlmSpiError"],
  ["MemoryServiceErrorKind", "LlmServiceErrorKind"],
  ["MemoryServiceError", "LlmServiceError"],
  ["MemoryServiceResult", "LlmServiceResult"],
  ["MemoryProviderInterface", "LlmProviderInterface"],
  ["MemoryProviderHealthStatus", "LlmProviderHealthStatus"],
  ["MemoryProviderHealth", "LlmProviderHealth"],
  ["MemoryLearningSettings", "LlmLearningSettings"],
  ["MemoryLearningSettingsRequest", "LlmLearningSettingsRequest"],
  ["MemoryRetrievalTrace", "LlmRetrievalTrace"],
  ["MemoryRetrievalHit", "LlmRetrievalHit"],
  ["MemoryRetrievalHitDraft", "LlmRetrievalHitDraft"],
  ["MemoryRetrievalRequest", "LlmRetrievalRequest"],
  ["MemoryRetrievalResult", "LlmRetrievalResult"],
  ["MemoryRetrieverKind", "LlmRetrieverKind"],
  ["MemoryContextPackRequest", "LlmContextPackRequest"],
  ["MemoryContextPack", "LlmContextPack"],
  ["MemoryFeedbackRequest", "LlmFeedbackRequest"],
  ["MemoryExtractionRequest", "LlmExtractionRequest"],
  ["MemoryLearningJob", "LlmLearningJob"],
  ["MemoryForgetRequest", "LlmForgetRequest"],
  ["MemoryForgetJob", "LlmForgetJob"],
  ["MemoryExportRequest", "LlmExportRequest"],
  ["MemoryExportJob", "LlmExportJob"],
  ["MemoryReviewRequest", "LlmReviewRequest"],
  ["MemoryHabitRequest", "LlmHabitRequest"],
  ["MemoryHabitList", "LlmHabitList"],
  ["MemoryHabit", "LlmHabit"],
  ["MemoryCandidateList", "LlmCandidateList"],
  ["MemoryCandidate", "LlmCandidate"],
  ["MemoryRecordSourceList", "LlmRecordSourceList"],
  ["MemoryRecordPatch", "LlmRecordPatch"],
  ["MemoryRecordRequest", "LlmRecordRequest"],
  ["MemoryRecordList", "LlmRecordList"],
  ["MemoryRecord", "LlmRecord"],
  ["MemoryEventRequest", "LlmEventRequest"],
  ["MemoryEvent", "LlmEvent"],
  ["MemorySpaceRequest", "LlmSpaceRequest"],
  ["MemorySpaceList", "LlmSpaceList"],
  ["MemorySpace", "LlmSpace"],
  ["MemoryCapabilities", "LlmCapabilities"],
  ["MemoryPageInfo", "LlmPageInfo"],
  ["MemoryType", "LlmRecordType"],
  ["MemoryOpenApi", "LlmOpenApi"],
  ["MemoryAppApi", "LlmAppApi"],
  ["MemoryBackendApi", "LlmBackendApi"],
  ["MemoryScopeContext", "LlmScopeContext"],
  ["MemoryService", "LlmService"],
  ["MemoryWebAuthMode", "LlmWebAuthMode"],
  ["AppendMemoryRetrievalTraceCommand", "AppendLlmRetrievalTraceCommand"],
  ["CreateMemoryCandidateCommand", "CreateLlmCandidateCommand"],
  ["ListMemoriesQuery", "ListLlmRecordsQuery"],
  ["ListCandidatesQuery", "ListLlmCandidatesQuery"],
  ["bootstrap_memory_database_from_env", "bootstrap_llm_database_from_env"],
  ["bootstrap_memory_database", "bootstrap_llm_database"],
  ["bootstrap_memory_data_plane_from_env", "bootstrap_llm_data_plane_from_env"],
  ["connect_memory_pool_from_env", "connect_llm_pool_from_env"],
  ["connect_and_bootstrap_memory_database_from_env", "connect_and_bootstrap_llm_database_from_env"],
  ["memory_no_embedding_mvp_test", "llm_no_embedding_mvp_test"],
  ["memory.open.", "llm.open."],
  ["memory.records", "llm.records"],
  ["memory.events", "llm.events"],
  ["memory.spaces", "llm.spaces"],
  ["memory.retrievals", "llm.retrievals"],
  ["memory.contextPacks", "llm.contextPacks"],
  ["memory.context_packs", "llm.context_packs"],
  ["memory.feedback", "llm.feedback"],
  ["memory.learning", "llm.learning"],
  ["memory.candidates", "llm.candidates"],
  ["memory.habits", "llm.habits"],
  ["memory.forget", "llm.forget"],
  ["memory.exports", "llm.exports"],
  ["memory.learningSettings", "llm.learningSettings"],
  ["memory.providerHealth", "llm.providerHealth"],
  ["memory.capabilities", "llm.capabilities"],
  ["memory.record.", "llm.record."],
  ["memory.space.", "llm.space."],
  ["memory.event.", "llm.event."],
  ["memory.retrieval.", "llm.retrieval."],
  ["memory.candidate.", "llm.candidate."],
  ["memory.habit.", "llm.habit."],
  ["memory.export.", "llm.export."],
  ["memory.forget.", "llm.forget."],
  ["memory.learning_settings.", "llm.learning_settings."],
  ["memory.provider_health.", "llm.provider_health."],
  ["memory.open.", "llm.open."],
  ["module_id: memory", "module_id: llm"],
  ['"moduleId": "memory"', '"moduleId": "llm"'],
  ["table_prefix: mem_", "table_prefix: llm_"],
  ['"tablePrefix": "mem_"', '"tablePrefix": "llm_"'],
  ["uk_mem_", "uk_llm_"],
  ["idx_mem_", "idx_llm_"],
  ["mem_record_source", "llm_record_source"],
  ["mem_retrieval_profile", "llm_retrieval_profile"],
  ["mem_retrieval_trace", "llm_retrieval_trace"],
  ["mem_retrieval_hit", "llm_retrieval_hit"],
  ["mem_context_pack", "llm_context_pack"],
  ["mem_implementation_profile", "llm_implementation_profile"],
  ["mem_provider_binding", "llm_provider_binding"],
  ["mem_eval_run", "llm_eval_run"],
  ["mem_audit_log", "llm_audit_log"],
  ["mem_outbox_event", "llm_outbox_event"],
  ["mem_candidate", "llm_candidate"],
  ["mem_record", "llm_record"],
  ["mem_habit", "llm_habit"],
  ["mem_entity", "llm_entity"],
  ["mem_edge", "llm_edge"],
  ["mem_index", "llm_index"],
  ["mem_policy", "llm_policy"],
  ["mem_space", "llm_space"],
  ["mem_event", "llm_event"],
  ["MemoryRecordStorePort", "LlmRecordStorePort"],
  ["MemoryEventStorePort", "LlmEventStorePort"],
  ["MemoryAuditStorePort", "LlmAuditStorePort"],
  ["MemoryOutboxStorePort", "LlmOutboxStorePort"],
  ["MemoryCandidateStorePort", "LlmCandidateStorePort"],
  ["MemoryHabitStorePort", "LlmHabitStorePort"],
  ["MemoryRetrievalTraceStorePort", "LlmRetrievalTraceStorePort"],
  ["load memory database", "load llm database"],
  ["read memory database", "read llm database"],
  ["memory database init", "llm database init"],
  ["memory database migrate", "llm database migrate"],
  ["read memory database config", "read llm database config"],
  ["create memory database pool", "create llm database pool"],
  ["memory database pool is not sqlite", "llm database pool is not sqlite"],
  ["memory id must be numeric", "llm record id must be numeric"],
  ["create memory", "create llm record"],
  ["AI memory", "AI LLM memory"],
  ["habit memory", "habit LLM memory"],
  ["embedding-optional AI memory", "embedding-optional intelligence LLM memory"],
  ["shared memory web auth", "shared llm web auth"],
  ["router-memory-common", "router-llm-common"],
  ["001-memory-core", "001-llm-core"],
  ["002-memory-learning", "002-llm-learning"],
  ["003-memory-retrieval", "003-llm-retrieval"],
  ["004-memory-provider", "004-llm-provider"],
  ["005-memory-governance", "005-llm-governance"],
  ["0001_memory_", "0001_llm_"],
  ["memory_phase1", "llm_phase1"],
  ["memory-topology", "llm-topology"],
  ["memory dev auth", "llm dev auth"],
  ["memory SDK manifests", "llm SDK manifests"],
  ["MemoryRuntimePlugin", "LlmRuntimePlugin"],
  ["MemoryCoreRuntime", "LlmCoreRuntime"],
  ["ReferenceMemoryRuntime", "ReferenceLlmRuntime"],
  ["AppendMemoryAuditCommand", "AppendLlmAuditCommand"],
  ["AppendMemoryOutboxCommand", "AppendLlmOutboxCommand"],
  ["AssembleMemoryContextCommand", "AssembleLlmContextCommand"],
  ["ExternalMemoryBridgePort", "ExternalLlmBridgePort"],
  ["ExternalMemoryImportCommand", "ExternalLlmImportCommand"],
  ["ExternalMemoryExportCommand", "ExternalLlmExportCommand"],
  ["ExternalMemoryDeleteCommand", "ExternalLlmDeleteCommand"],
  ["ExternalMemoryShadowReadCommand", "ExternalLlmShadowReadCommand"],
  ["ExternalMemoryShadowReadResult", "ExternalLlmShadowReadResult"],
  ["ExternalMemoryExportResult", "ExternalLlmExportResult"],
  ["ExternalMemoryImportResult", "ExternalLlmImportResult"],
  ["ExternalMemoryDeleteReceipt", "ExternalLlmDeleteReceipt"],
  ["MemoryContextAssemblerPort", "LlmContextAssemblerPort"],
  ["MemoryEvaluationPort", "LlmEvaluationPort"],
  ["MemoryIndexPort", "LlmIndexPort"],
  ["MemoryRetrieverPort", "LlmRetrieverPort"],
  ["RetrieveMemoryAuditQuery", "RetrieveLlmAuditQuery"],
  ["RunMemoryEvalCommand", "RunLlmEvalCommand"],
  ["ListPendingMemoryOutboxQuery", "ListPendingLlmOutboxQuery"],
  ["MarkMemoryOutboxPublishedCommand", "MarkLlmOutboxPublishedCommand"],
  ["MarkMemoryOutboxFailedCommand", "MarkLlmOutboxFailedCommand"],
  ["MemoryAuditRecord", "LlmAuditRecord"],
  ["MemoryDeletionReceipt", "LlmDeletionReceipt"],
  ["MemoryEvalRunResult", "LlmEvalRunResult"],
  ["mem_learning_job", "llm_learning_job"],
  ["`mem_`", "`llm_`"],
  ["prefix: 'mem_'", "prefix: 'llm_'"],
  ["tablePrefix = 'mem_'", "tablePrefix = 'llm_'"],
  ["domain: 'memory'", "domain: 'llm'"],
  ['{memoryId:', '{recordId:'],
  ['"memoryId"', '"recordId"'],
  ['memoryIds', 'recordIds'],
  ["/memories/", "/records/"],
  ["RECORDS", "RECORDS"],
  ["/memories", "/records"],
  ["memories.list", "records.list"],
  ["memories.create", "records.create"],
  ["memories.retrieve", "records.retrieve"],
  ["memories.update", "records.update"],
  ["memories.delete", "records.delete"],
  ["memories.sources.list", "records.sources.list"],
];

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (skipDirs.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else if (textExtensions.has(path.extname(entry.name))) files.push(full);
  }
  return files;
}

let changed = 0;
for (const file of walk(root)) {
  if (file.includes(`${path.sep}tools${path.sep}align_llm_domain.mjs`)) continue;
  if (file.includes(`${path.sep}tools${path.sep}bootstrap_from_memory`)) continue;
  if (file.includes(`${path.sep}tools${path.sep}transform_memory`)) continue;
  let content = fs.readFileSync(file, "utf8");
  const original = content;
  for (const [from, to] of replacements) {
    content = content.split(from).join(to);
  }
  if (content !== original) {
    fs.writeFileSync(file, content.replace(/\r\n/g, "\n"), "utf8");
    changed += 1;
    console.log(`aligned ${path.relative(root, file)}`);
  }
}

console.log(`domain alignment touched ${changed} files`);
